### ISSUE TITLE
Sniper did not trigger

### ISSUE THREAD

**Issue by cryptostevo4** [CryptoGnome/Limit-Sniper#17]
[
  {
    "ADDRESS": "0x1190074795DAD0E61b61270De48e108427f8f817",
    "SYMBOL": "CMERGE",
    "BUYAMOUNT": ".4",
    "MULTIPLEBUYS": "true",
    "BUYCOUNT": "4",
    "RUGCHECK": "false"
  }
]

error log

INFO: 2021-07-16 18:08:43,938 Current $LIMIT Tokens Staked = 100.98457063878817
ERROR: 2021-07-16 18:18:21,189 Could not find any function with matching selector
Traceback (most recent call last):
  File "sniper.py", line 433, in scan
  File "eth_utils\decorators.py", line 18, in _wrapper
  File "web3\contract.py", line 465, in decode_function_input
  File "eth_utils\decorators.py", line 18, in _wrapper
  File "web3\contract.py", line 458, in get_function_by_selector
  File "web3\contract.py", line 1679, in get_function_by_identifier
ValueError: Could not find any function with matching selector

**Comment by CryptoGnome** [comment]
the contract was not verified so the scan failed, you can disable rug checker to trade unverified contracts
