### ISSUE TITLE
Issue 0.18

### ISSUE THREAD

**Issue by alefantozzi** [CryptoGnome/Limit-Sniper#2]
getting this error when launching it (using same settings/tokens of previous versions, which were working):

Traceback (most recent call last):
  File "sniper.py", line 40, in <module>
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 10 column 1 (char 499)
[211728] Failed to execute script sniper

**Comment by alefantozzi** [comment]
never mind, found the problem (tokens.json  has changed)
