### ISSUE TITLE
ValueError: Could not find any function with matching selector

### ISSUE THREAD

**Issue by NachoJSBSC** [CryptoGnome/Limit-Sniper#3]
ERROR: 2021-07-06 17:56:15,866 Could not find any function with matching selector
Traceback (most recent call last):
  File "sniper.py", line 402, in scan
  File "eth_utils\decorators.py", line 18, in _wrapper
  File "web3\contract.py", line 466, in decode_function_input
  File "eth_utils\decorators.py", line 18, in _wrapper
  File "web3\contract.py", line 459, in get_function_by_selector
  File "web3\contract.py", line 1680, in get_function_by_identifier
ValueError: Could not find any function with matching selector

--------------

[
  {
    "ADDRESS": "0xEAc9873291dDAcA754EA5642114151f3035c67A2",
    "SYMBOL": "DCB",
    "BUYAMOUNT": "10",
	"MULTIPLEBUYS": "true",
    "BUYCOUNT": "1",
	 "RUGCHECK": "false"

  }
]

**Comment by NachoJSBSC** [comment]
https://bscscan.com/tx/0xa18e42883bd27f1a3c024073454e478f043d520e30cf26def7685134edc8dc71

the failed transaction

**Comment by CryptoGnome** [comment]
10 BNB must have been max TX size bro

**Comment by NachoJSBSC** [comment]
ok, thanks for the answer. what max transaction size would you recommend? or 10x 1 bnb?
