### ISSUE TITLE
Error sniping. Auto close

### ISSUE THREAD

**Issue by deltaparadise** [CryptoGnome/Limit-Sniper#33]
I was trying to snipe a launch and the bot closes when the liquidity was added.
ERROR: 2021-10-04 16:02:40,582 
Traceback (most recent call last):
  File "sniper.py", line 740, in <module>
  File "sniper.py", line 731, in run
  File "sniper.py", line 466, in scan
  File "sniper.py", line 641, in buy_many
MemoryError
![imagen](https://user-images.githubusercontent.com/91908575/135896848-1c767681-ce03-4621-b28b-fb733aa6bd72.png)
![imagen](https://user-images.githubusercontent.com/91908575/135896892-c2710ec4-ac51-4d58-b969-4a48af8b177b.png)

**Comment by deltaparadise** [comment]
Its happening again. 
ERROR: 2021-10-05 14:02:10,422 
Traceback (most recent call last):
  File "sniper.py", line 740, in <module>
  File "sniper.py", line 731, in run
  File "sniper.py", line 476, in scan
  File "sniper.py", line 551, in buy
MemoryError

**Comment by deltaparadise** [comment]
The error was on my pc. Some compatibility problem. I have tried on another pc and it works perfectly.
